version: "3.9"

services:
  database: #ESSE É O NOME DO SERVICE QUE DEVE ESTAR NO ARQUIVO DE CRIAÇÃO DE CONEXÃO
    image: postgres
    container_name: database_progweb
    restart: always
    ports:
      - 49153:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=ecommerce
    volumes:
      - pgdata:/data/postgres
  
  app:
    build: .
    container_name: ecommerce
    ports:
      - 3000:3000
      - 9229:9229 #Você pode inserir essa porta tbm pra poder usar o debug
    volumes:
      - .:/usr/app
    environment:
      - DATABASE_URL=postgres://postgres:postgrespw@database:5432/ecommerce?schema=public
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local